"""Migración Inicial

Revision ID: 57d27879b8cc
Revises: 
Create Date: 2026-01-19 20:53:52.168159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d27879b8cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('preguntas_recuperacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('texto')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_casa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('imagen_perfil', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('contrasena', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('domicilio', sa.String(length=255), nullable=False),
    sa.Column('pregunta_recuperacion_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_recuperacion', sa.String(length=255), nullable=False),
    sa.Column('permitir_huella', sa.Integer(), nullable=False),
    sa.Column('token_publico', sa.String(length=255), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('estado_cuenta', sa.String(length=20), nullable=False),
    sa.Column('nombre_titular', sa.String(length=120), nullable=False),
    sa.Column('numero_encriptado', sa.String(length=255), nullable=False),
    sa.Column('fecha_expiracion', sa.String(length=7), nullable=False),
    sa.Column('marca', sa.String(length=20), nullable=False),
    sa.Column('ultimos_4', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['pregunta_recuperacion_id'], ['preguntas_recuperacion.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('username')
    )
    op.create_table('usuario_hobbies',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hobby_id'], ['hobbies.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'hobby_id')
    )
    op.create_table('usuario_tipos_casa',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_casa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_casa_id'], ['tipos_casa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'tipo_casa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_tipos_casa')
    op.drop_table('usuario_hobbies')
    op.drop_table('usuario')
    op.drop_table('tipos_casa')
    op.drop_table('roles')
    op.drop_table('preguntas_recuperacion')
    op.drop_table('hobbies')
    # ### end Alembic commands ###
